# Generated by Django 5.2.1 on 2025-05-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_usuarios', '0004_alter_usuario_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
